<a href="https://colab.research.google.com/github/aot-abhishekyadav/Machine-Learning-Fundamentals/blob/main/03-Numpy/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python'''

'NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python'

In [ ]:
'''What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type'''

'What is an array\nAn array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type'

In [ ]:
# First we have to import numpy
import numpy as np

In [ ]:
lst = [1,2,3,4]
np.array(lst) # it creates 1 dimensional array hum identify kar skte hai 1D array yai dekh ki uski end mai kitne square brackets hai agr uske end mai 2 square brackets hongai to vo 2D array hoga

array([1, 2, 3, 4])

In [ ]:
arr = np.array(lst)
print(arr)

[1 2 3 4]


In [ ]:
type(arr) # numpy.ndarray = n dimensional array

numpy.ndarray

In [ ]:
arr.shape

(4,)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.itemsize #The arr.itemsize attribute in NumPy returns the size in bytes of each element in the array. In the case of the arr array, which contains integers, the output of 8 indicates that each integer element occupies 8 bytes in memory.

8

In [ ]:
lst1 = [1,2,3,4]
lst2 = [5,6,7,8]
lst3 = [9,10,11,12]
arr1 = np.array([lst1,lst2,lst3]) # it creates 2 dimensional array
arr1 # 2D array end 2 square btrackets ho rha hai

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr1.shape # 3 rows and 4 columns

(3, 4)

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
# Indexing
#arr[2]
print(arr[2]) # It print 3rd elemnt of array

3


In [ ]:
arr[3] = 5
arr # we can also change value in array

array([1, 2, 3, 5])

In [ ]:
arr[1:] # it gives value from idexing of 1

array([2, 3, 5])

In [ ]:
# We can also specify the range
arr[1:3] # it gives value from index 1 to 2

array([2, 3])

In [ ]:
arr[-1]  # it gives us last value of array
#print(arr[-1])

np.int64(5)

In [ ]:
arr[:-1] # : iski vjh sai hume yai 5 ko chor kai sari value dega aaray ki

array([1, 2, 3])

In [ ]:
arr[::] # :: it gives us all the value of array

array([1, 2, 3, 5])

In [ ]:
arr[::-1] # :: column kai saath agr hum indexing number dalte hai to vo ulti array print kar deta hai

array([5, 3, 2, 1])

In [ ]:
arr[::-2] # -2 ki vjh sai yai array intial value sai 2 value jump lai kai print ho rha hai lekin hoga piche sai hii

array([5, 2])

In [ ]:
arr[::-3]

array([5, 1])

In [ ]:
arr[2:]

array([3, 5])

In [ ]:
# Multil array indexing
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr1[:,1] # it give us the value of 1st column : that means row

array([ 2,  6, 10])

In [ ]:
arr1[1:,1:3] # yai hume 1st row sai aur 1 column sai 2nd column tak value extract kar kai dai dega

array([[ 6,  7],
       [10, 11]])

In [ ]:
arr1[0:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [ ]:
arr1[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [ ]:
arr1[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [ ]:
arr1[:,1:3].shape

(3, 2)

In [ ]:
arr1[:,[0,3]] # : → all rows
              # [0, 3] → value from only columns 0 and 3

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [ ]:
# reshaping of an array
arr1.reshape(4,3) # 4 rows and 3 columns

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr1.reshape(2,6) # 2 rows and 6 columns

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
arr1.reshape(1,12) # 1 row and 12 columns

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
#arr1.reshape(4,5) # It give us error because no of elemnts after multiply same hona chi hai

In [ ]:
# Mechanism to crate an array
np.arange(1,10,1) # 1 for start 10 for stop and 1 for step size

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,10,1).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1, 26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# multiplying array
arr*arr

array([ 1,  4,  9, 25])

In [ ]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [ ]:
arr1*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [ ]:
# adding array
arr1 + arr1

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [ ]:
# Dividing array
arr1/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 5. , 5.5, 6. ]])

In [ ]:
# mean value of array
mean_value = np.mean(arr1)
print(mean_value)

6.5


In [ ]:
# max value of array and its index
max_value = np.max(arr1)
index = np.argmax(arr1)

print(f"The maximum value of array is {max_value} and its index is {index}")

The maximum value of array is 12 and its index is 11


In [ ]:
min_value = np.min(arr1)
index = np.argmin(arr1)

print(f"The minimum value of array is {min_value} and its index is {index}")

The minimum value of array is 1 and its index is 0


In [ ]:
# creating an array fill with 1
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# creating an array fill with zeroes
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
b = np.ones((3,3), dtype = 'int')
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
c = np.array([1,2,3])
d = c + b
d

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [ ]:
# creating array from random numver
np.random.randint(1,30,4) # it creates an array b/w 1 to 30 of size an array 4

array([25, 23, 28, 20])

In [ ]:
np.random.randint(1,30,4).reshape(2,2)

array([[14, 20],
       [20,  6]])

In [ ]:
a = np.random.randint(1,20, size = (3,3)) # creating Multidimensional array with
a                                         # help of random module

array([[ 3,  9,  5],
       [16,  5, 12],
       [17, 11, 16]])

In [ ]:
# determinant of array
det = np.linalg.det(a)  # we can calculate only determinant of square array
print(det)

-169.0


In [ ]:
np.random.random_sample((4,4)) # it give us random value from 0 to 1

array([[0.89109807, 0.74928543, 0.17424746, 0.07689036],
       [0.16013399, 0.46621337, 0.90487952, 0.39138681],
       [0.0344071 , 0.64005806, 0.7371777 , 0.34779906],
       [0.30209043, 0.65346386, 0.4857413 , 0.52486902]])

In [ ]:

#  creating a 2D array of shape(5,5)

f = np.array([[1,2,3,4,5,],[6,7,8,9,10,],[11,12,13,14,15,],[16,17,18,19,20,],[21,22,23,24,25]])
print(f)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# EDA
arr

array([1, 2, 3, 5])

In [ ]:
arr>2 # it tells us which element in array is grater than 2

array([False, False,  True,  True])

In [ ]:
arr[arr>2] # it give us the element which is greater than 2

array([3, 5])